---
- name: Ensure the group exists
  ansible.builtin.group:
    name: "{{ group_name }}"
    state: present

- name: Ensure additional group exists
  ansible.builtin.group:
    name: "{{ additional_group }}"
    state: present

- name: Create user accounts and add to groups
  ansible.builtin.user:
    name: "{{ item.username }}"
    groups: "{{ group_name }},{{ additional_group }}"
    append: yes
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: ".ssh/id_rsa"
  loop: "{{ users }}"
  when: ansible_os_family != "Windows"

- name: Set up authorized keys for the user
  ansible.builtin.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ lookup('file', item.username + '.ssh/id_rsa') }}"
  loop: "{{ users }}"
