---
- name: Install Apache web server
  ansible.builtin.yum:
    name: httpd
    state: present

- name: Create HTML files on the automation server
  ansible.builtin.copy:
    dest: "/var/www/html/index.html"
    content: "This is the node {{ ansible_fqdn }}"
    mode: '0444'
  loop:
    - vm1.html
    - vm2.html
    - vm3.html
  when: inventory_hostname == item.replace('.html', '')
  notify: restart apache

- name: Ensure Apache is started and enabled
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: restart apache
  ansible.builtin.service:
    name: httpd
    state: restarted

