all:
  children:
    linux:
      hosts:
        N01459693-c-vm1:
          ansible_host: 40.112.56.188
          ansible_user: adminuser
          ansible_ssh_private_key_file: N01459693_key.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

        N01459693-c-vm2:
          ansible_host: 40.112.56.225
          ansible_user: adminuser
          ansible_ssh_private_key_file: N01459693_key.pem
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

    windows:
      hosts:
        windows_vm:
          ansible_host: 20.232.176.110
          ansible_user: adminuser
          ansible_password: P@nakokta645
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore

